### ISSUE TITLE
Add Julia graphing?

### ISSUE THREAD

**Issue by cormullion** [Microbiology/JuliaPerlBenchmark#4]
I thought of adding a short Julia snippet for plotting the results (since I don't understand R). I got this far:

```
using DataFrames, Plots
f = open("time.log")
timings = readtable(f,  
    separator = '\t', 
    header = false, 
    names=[:realsysuser, :timing, :language, :number])
close(f)

sort!(timings, cols = [:number, :realsysuser])

perltimings = timings[timings[:language] .== "Perl", :][:timing]
juliatimings = timings[timings[:language] .== "Julia", :][:timing]

plot([perltimings juliatimings], label=["Perl" "Julia"])
```

but I'm not 100% sure I ran the benchmarks properly. Anyway, here it is, for what it's worth!

![plot](https://cloud.githubusercontent.com/assets/52289/16452060/71106e78-3dfe-11e6-839b-21d1bbb3c55a.png)

**Comment by Microbiology** [comment]
Thanks, and great idea! I don't have experience graphing with Julia, but it looks nice. I'm not sure what is going on with the x-axis. Are the values being treated as discrete categories instead of continuous values? If you figure it out, can you create a pull request so that we can integrate it into the main repo?

**Comment by cormullion** [comment]
I did a PR to make a graph. It looks like the benchmark script starts up Julia each time, which might be  inefficient. Also I don't know the difference between real/sys/user timings. Good luck!

**Comment by Microbiology** [comment]
Yeah there might be a better way to do it without restarting every time. That would be cool to implement.

Here is an explanation of the different parameters on SO. I see though that it looks like the plot was combining all of the times without splitting them by category.

http://stackoverflow.com/questions/556405/what-do-real-user-and-sys-mean-in-the-output-of-time1
